[2024-04-01T05:32:24.010+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:32:16.453924+00:00 [queued]>
[2024-04-01T05:32:24.016+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:32:16.453924+00:00 [queued]>
[2024-04-01T05:32:24.017+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-04-01T05:32:24.026+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 05:32:16.453924+00:00
[2024-04-01T05:32:24.031+0000] {standard_task_runner.py:57} INFO - Started process 1474 to run task
[2024-04-01T05:32:24.033+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T05:32:16.453924+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmpsp6y4hpu']
[2024-04-01T05:32:24.034+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask task_1_runConsumer
[2024-04-01T05:32:24.070+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T05:32:16.453924+00:00 [running]> on host 977df1ccf323
[2024-04-01T05:32:24.124+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:32:16.453924+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T05:32:16.453924+00:00'
[2024-04-01T05:32:24.125+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T05:32:24.126+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/producer.py']
[2024-04-01T05:32:24.136+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T05:32:24.227+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T05:32:24.227+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/producer.py", line 1, in <module>
[2024-04-01T05:32:24.227+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2024-04-01T05:32:24.228+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2024-04-01T05:32:24.230+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T05:32:24.238+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T05:32:24.241+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T053216, start_date=20240401T053224, end_date=20240401T053224
[2024-04-01T05:32:24.250+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task task_1_runConsumer (Bash command failed. The command returned a non-zero exit code 1.; 1474)
[2024-04-01T05:32:24.285+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T05:32:24.304+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
